name = "DDV"
description = "Blog theme inspered by Drew DeVault's blog"
license = "MIT"
homepage = "https://github.com/getzola/hyde"
min_version = "0.4.0"
demo = "https://ddv-theme.github.io"

[extra]

[author]
name = "Eugene Lebedev"
homepage = "https://tinyops.ru"